name: virgin-tech-test
channels:
  - conda-forge
dependencies:
  - _py-xgboost-mutex=2.0
  - aiohttp=3.8.1
  - aiosignal=1.2.0
  - appnope=0.1.2
  - asttokens=2.0.5
  - async-timeout=4.0.2
  - attrs=21.4.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - black=22.1.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2021.10.8
  - cachetools=5.0.0
  - certifi=2021.10.8
  - cffi=1.15.0
  - charset-normalizer=2.0.12
  - click=8.0.4
  - cryptography=36.0.1
  - cycler=0.11.0
  - dataclasses=0.8
  - debugpy=1.5.1
  - decorator=5.1.1
  - entrypoints=0.4
  - executing=0.8.2
  - fonttools=4.29.1
  - freetype=2.10.4
  - frozenlist=1.3.0
  - giflib=5.2.1
  - google-api-core=2.5.0
  - google-auth=2.6.0
  - google-cloud-core=2.2.2
  - google-cloud-storage=2.1.0
  - google-crc32c=1.1.2
  - google-resumable-media=2.1.0
  - googleapis-common-protos=1.54.0
  - grpcio=1.44.0
  - idna=3.3
  - iniconfig=1.1.1
  - ipykernel=6.9.1
  - ipython=8.0.1
  - jbig=2.1
  - jedi=0.18.1
  - joblib=1.1.0
  - jpeg=9e
  - jupyter_client=7.1.2
  - jupyter_core=4.9.2
  - kiwisolver=1.3.2
  - lcms2=2.12
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcxx=12.0.1
  - libdeflate=1.10
  - libffi=3.4.2
  - libgfortran=5.0.0.dev0
  - libgfortran5=11.0.1.dev0
  - liblapack=3.9.0
  - libopenblas=0.3.18
  - libpng=1.6.37
  - libprotobuf=3.19.4
  - libsodium=1.0.18
  - libtiff=4.3.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.13
  - libxgboost=1.5.1
  - libzlib=1.2.11
  - llvm-openmp=13.0.1
  - lz4-c=1.9.3
  - matplotlib=3.5.1
  - matplotlib-base=3.5.1
  - matplotlib-inline=0.1.3
  - multidict=6.0.2
  - munkres=1.1.4
  - mypy_extensions=0.4.3
  - ncurses=6.3
  - nest-asyncio=1.5.4
  - numpy=1.22.2
  - openjpeg=2.4.0
  - openssl=1.1.1l
  - packaging=21.3
  - pandas=1.4.1
  - parso=0.8.3
  - pathspec=0.9.0
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.0.1
  - pip=22.0.3
  - platformdirs=2.5.1
  - pluggy=1.0.0
  - prompt-toolkit=3.0.27
  - protobuf=3.19.4
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py=1.11.0
  - py-xgboost=1.5.1
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.21
  - pygments=2.11.2
  - pyopenssl=22.0.0
  - pyparsing=3.0.7
  - pysocks=1.7.1
  - pytest=7.0.1
  - python=3.10.2
  - python-dateutil=2.8.2
  - python_abi=3.10
  - pytz=2021.3
  - pyu2f=0.1.5
  - pyzmq=22.3.0
  - readline=8.1
  - requests=2.27.1
  - rsa=4.8
  - scikit-learn=1.0.2
  - scipy=1.8.0
  - setuptools=60.9.3
  - six=1.16.0
  - sqlite=3.37.0
  - stack_data=0.2.0
  - threadpoolctl=3.1.0
  - tk=8.6.12
  - tomli=2.0.1
  - tornado=6.1
  - traitlets=5.1.1
  - typed-ast=1.5.2
  - typing-extensions=4.1.1
  - typing_extensions=4.1.1
  - tzdata=2021e
  - unicodedata2=14.0.0
  - urllib3=1.26.8
  - wcwidth=0.2.5
  - wheel=0.37.1
  - xgboost=1.5.1
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - yarl=1.7.2
  - zeromq=4.3.4
  - zlib=1.2.11
  - zstd=1.5.2
